CREATE TABLE IF NOT EXSITS user(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50),
    email VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
);

CREATE TABLE IF NOT EXISTS deck(
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(50) NOT NULL,
    size INT NOT NULL
);

CREATE TABLE IF NOT EXISTS flashcard(
    id INT AUTO_INCREMENT PRIMARY KEY,
    deckid INT NOT NULL,
    term VARCHAR(100) NOT NULL,
    definition TEXT NOT NULL,
    FOREIGN KEY (deckid) REFERENCES deck(id) ON DELETE CASCADE ON UPDATE CASCADE
);